#!/bin/sh

adb shell "run-as com.transistorsoft.backgroundgeolocation.react cat /data/user/0/com.transistorsoft.backgroundgeolocation.react/databases/transistor_location_manager" > transistor_location_manager.db

